const initialNodes = [
        { id: '1', type: 'startBlock', position: { x: 0, y: 0 }, data: { label: '1' } },
        { id: '2', type: 'endBlock', position: { x: 0, y: 100 }, data: { label: '2' } },
        { id: '3', type: 'ifBlock', position: { x: 0, y: 200 }, data: { label: '3', type: 'bool' } },

        { id: '14', type: 'onBlock', position: { x: 0, y: 300 }, data: { label: '14', type: 'recurrence-date'  } },
        { id: '15', type: 'forEachBlock', position: { x: 0, y: 400 }, data: { label: '15', type: 'array'  } },
      
        { id: '4', type: 'forBlock', position: { x: 0, y: 500 }, data: { label: '4', type: 'bool' } },
        { id: '17', type: 'atBlock', position: { x: 0, y: 1600 }, data: { label: '17', type: '' } },
        { id: '5', type: 'equalBlock', position: { x: 0, y: 600 }, data: { label: '5', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '6', type: 'notEqualBlock', position: { x: 0, y: 700 }, data: { label: '6', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '7', type: 'superiorBlock', position: { x: 0, y: 800 }, data: { label: '7', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '8', type: 'inferiorBlock', position: { x: 0, y: 900 }, data: { label: '8', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '9', type: 'superiorOrEqualBlock', position: { x: 0, y: 1000 }, data: { label: '9', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '10', type: 'inferiorOrEqualBlock', position: { x: 0, y: 1100 }, data: { label: '10', type: '', typeOutput: 'bool', value: 'false' } },
        { id: '11', type: 'numberBlock', position: { x: 0, y: 1200 }, data: { label: '11', value: 0, type: 'number'} },
        { id: '99', type: 'numberBlock', position: { x: 500, y: 1200 }, data: { label: '99', value: 0, type: 'number'} },
        { id: '12', type: 'booleanBlock', position: { x: 0, y: 1300 }, data: { label: '12', value: false, type: 'bool'} },
        { id: '97', type: 'booleanBlock', position: { x: 500, y: 1300 }, data: { label: '97', value: false, type: 'bool'} },
        { id: '13', type: 'stringBlock', position: { x: 0, y: 1400 }, data: { label: '13', value: 'gazo', type: 'str'} },
        { id: '98', type: 'stringBlock', position: { x: 500, y: 1400 }, data: { label: '98', value: '', type: 'str'} },
        { id: '20', type: 'arrayBlock', position: { x: 0, y: 1700 }, data: { label: '20', value: '', type: 'array'} },
        { id: '96', type: 'arrayBlock', position: { x: 500, y: 1700 }, data: { label: '96', value: '', type: 'array'} },
        { id: '21', type: 'objectBlock', position: { x: 0, y: 1800 }, data: { label: '21', value: '', type: 'object'} },
        { id: '95', type: 'objectBlock', position: { x: 500, y: 1800 }, data: { label: '95', value: '', type: 'object'} },
        { id: '16', type: 'numberToBoolBlock', position: { x: 0, y: 1500 }, data: { label: '16', type: 'number', typeOutput: 'bool', value: false} },
        { id: '26', type: 'recurrenceBlock', position: { x: 0, y: 1900 }, data: { label: '26', type: 'recurrence-date', value: {}} },
        { id: '27', type: 'dateBlock', position: { x: 0, y: 2000 }, data: { label: '27', type: 'recurrence-date', value: {}} },
        { id: '28', type: 'numberToStringBlock', position: { x: 0, y: 2100 }, data: { label: '28', type: 'number', typeOutput: 'str', value: ''} },
        { id: '29', type: 'stringToNumberBlock', position: { x: 0, y: 2200 }, data: { label: '29', type: 'str', typeOutput: 'number', value: ''} },
        { id: '30', type: 'stringBuilderBlock', position: { x: 0, y: 2300 }, data: { label: '30', type: 'str', typeOutput: 'str', value: ''} },
    ];