name: Mirror FrontEnd

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: AREA-LinkEase/project

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Force Install GIT latest
        run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.MIRROR_URL }}
          ref: 'main'

      - name: setup user git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: delete directory
        run: |
          rm -rf FrontEnd || exit 0

      - name: move to correct directory
        run: |
          mkdir FrontEnd && cd ./FrontEnd

      - name: clone the current repository
        uses: actions/checkout@v2

      - name: delete useless folder
        run: |
          rm -rf .git
          cd ..
          ls -lR

      - name: push
        run: |
          git push
