name: Mirror FrontEnd

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: AREA-LinkEase/project

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.MIRROR_URL }}
          path: './project'

      - name: setup user git
        run: |
          cd project
          ls -la
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: delete directory
        run: |
          rm -rf FrontEnd || exit 0

      - name: clone the current repository
        uses: actions/checkout@v2
        with:
          path: "./FrontEnd"

      - name: delete useless folder
        run: |
          rm -rf ./FrontEnd/.git
          ls -lR

      - name: push
        run: |
          git add .
          git commit -m "ADD FrontEnd"
          git push
