name: Mirror FrontEnd

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: AREA-LinkEase/project

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.MIRROR_URL }}
          ref: 'main'

      - name: setup user git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: move to correct directory
        run: |
          rm -rf FrontEnd || exit 0
          mkdir FrontEnd
          cd ./FrontEnd

      - name: clone the current repository
        uses: actions/checkout@v2

      - name: delete useless folder
        run: |
          rm -rf .git

      - name: push
        run: |
          git push origin master
